spring: 
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
logging:
    level:
        com:
            ibm:
                demo: trace
        org:
            springframework:
                web: trace
features:
  exclusiveOffers: true
  flashSale: true
  bluetoothEarPhones: true
ibmcloud:
    appconfig:
        guid: <guid>
        apikey: <apikey>
        env: dev
        collection: shoppers-delight


 